ChitCare.UI/ChitCare.UI.Web/Areas/Masters/Controllers/CommonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ChitCare.UI.ViewModels.Models;
using System.Threading.Tasks;
using ChitCare.UI.Web.Controllers;

namespace ChitCare.UI.Web.Areas.Masters.Controllers
{
    public class CommonController : ChitCareController
    {
        // GET: Masters/Common
        public PartialViewResult Menu()
        {
            
            List<MenuViewModel> menuList = CHITCAREHttpClient.GetRequestSync<List<MenuViewModel>>("Menu/MainMenu");
            return PartialView(menuList);
        }
        public async Task<JsonResult> GetBranches()
        {
            return Json(await CHITCAREHttpClient.GetRequest<List<BranchViewModel>>("Common/Branches", null), JsonRequestBehavior.AllowGet);
        }
        public async Task<JsonResult> GroupsAutoList(string prefix, int BranchId)
        {

            return Json(await CHITCAREHttpClient.GetRequest<List<GroupsViewModel>>("Common/AutoListGroups", multiFormURIQueryString: "Prefix=" + prefix + "&Id=" + BranchId), JsonRequestBehavior.AllowGet);
        }
    }
}

ChitCare.UI/ChitCare.UI.Web/Areas/Masters/Controllers/MemberController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Threading.Tasks;
using ChitCare.UI.Web.Controllers;
using ChitCare.UI.ViewModels.Models;
namespace ChitCare.UI.Web.Areas.Masters.Controllers
{
    public class MemberController : ChitCareController
    {
        // GET: Masters/Member
        public ActionResult RegistrationEntry(int id = 0)
        {
            ViewBag.Id = id;
            return View();
        }

        [HttpPost]
        public async Task<JsonResult> MemberRegistrationEntry(PersonViewModel personViewModel)
        {


            await CHITCAREHttpClient.SendRequest<PersonViewModel, string>("Persons/Insert", personViewModel);

            return Json(true, JsonRequestBehavior.AllowGet);
        }

        public ActionResult MemberRegistrationList(int Type = 0)
        {
            ViewBag.ListType = Type;
            return View();
        }


        public async Task<JsonResult> GetMemberRegistrationList(string BranchId, string Prefix, DateTime Fdate, DateTime ToDate, int ListType)

        {

            string fdate = Fdate.ToString();
            string todate = ToDate.ToString();
            List<PersonsDataViewModel> pDataList = await CHITCAREHttpClient.GetRequest<List<PersonsDataViewModel>>("Persons/GetPersons", multiFormURIQueryString: "BranchId=" + BranchId + "&Prefix=" + Prefix + "&Fdate=" + fdate + "&ToDate=" + todate + "&ListType=" + ListType);
            return Json(pDataList, JsonRequestBehavior.AllowGet);
        }

        public async Task<JsonResult> MemberRegistrationEdit(int PersonId)
        {

            return Json(await CHITCAREHttpClient.GetRequest<PersonViewModel>("Persons/EditPerson", PersonId), JsonRequestBehavior.AllowGet);
        }

        public async Task<JsonResult> ActivateOrDeactivatePerson(string Type, int PersonId)
        {
            await CHITCAREHttpClient.GetRequest("Masters/ActivateOrDeactivatePerson", multiFormURIQueryString: "Type=" + Convert.ToInt32(Type) + "&PersonId=" + PersonId);
            return Json(true, JsonRequestBehavior.AllowGet);
        }

    }
}

ChitCare.UI/ChitCare.UI.Web/Controllers/ChitCareController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ChitCare.UI.Common.Cache;
using ChitCare.UI.Common.SimpleHttpClient;
using Common.IoC;
namespace ChitCare.UI.Web.Controllers
{
    public class ChitCareController : Controller
    {
        // GET: ChitCare
        [SimpleIoCPropertyInject]
        public ICHITCAREHttpClient CHITCAREHttpClient { get; set; }
       
    }
}

ChitCare.UI/ChitCare.UI.Web/Areas/Masters/Views/Common/Menu.cshtml
@using ChitCare.UI.ViewModels.Models;
@model IEnumerable<ChitCare.UI.ViewModels.Models.MenuViewModel>


<nav class="navbar navbar-inverse navbar-static-top" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <div class="logo">
            <span class="l l1"></span>
            <span class="l l2"></span>
            <span class="l l3"></span>
            <span class="l l4"></span>
            <span class="l l5"></span>
        </div>
        <a class="navbar-brand" href="index.html">Chitcare</a>
    </div>
    <!-- /.navbar-header -->
    <ul class="nav navbar-top-links hidden-xs navbar-left">
        <li class="nav-item">
            <a class="nav-link text-center" id="sidenavToggler">
                <i class="fa fa-bars"></i>
            </a>
        </li>
    </ul>
    <ul class="nav navbar-top-links nav-center">
        <li class="dropdown" style="text-align:center">

            <h4>Chitcare Demo</h4>

        </li>
    </ul>
    <ul class="nav navbar-top-links navbar-right">

        <li class="dropdown">
            <a href="#">
                FY : <span>01/04/2017-31/03/2018</span>
            </a>
        </li>
        <!-- /.dropdown -->
        <li class="dropdown">
            <a href="#">
                IST : <span>@DateTime.Now.Date</span>
            </a>
        </li>
        <!-- /.dropdown -->

        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-user">
                <li>
                    <a href="#"><i class="fa fa-user fa-fw"></i> Mr. Essel</a>
                </li>
                <li>
                    <a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="login.html"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                </li>
            </ul>
            <!-- /.dropdown-user -->
        </li>
        <!-- /.dropdown -->
    </ul>
    <!-- /.navbar-top-links -->

    <div class="navbar-default sidebar" role="navigation">
        <div class="sidebar-nav navbar-collapse">
            <ul class="nav" id="side-menu">

                <li>
                    <a href="index.html" class="menu-item"><i class="fa fa-home"></i> <span>Home</span></a>
                </li>
                <li>
                    <a href="#" class="menu-item"><i class="fa fa-heart-o"></i> <span>Favorites</span><span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level nav-second-level-sm collapse">
                        <li>
                            <a href="#">Second Level Item</a>
                        </li>
                        <li>
                            <a href="#">Second Level Item</a>
                        </li>
                        <li>
                            <a href="#">Third Level <span class="fa arrow"></span></a>
                            <ul class="nav collapse mobile-3rd-level">
                                <li>
                                    <a href="#">Third Level Item</a>
                                </li>
                                <li>
                                    <a href="#">Third Level Item</a>
                                </li>
                                <li>
                                    <a href="#">Third Level Item</a>
                                </li>
                                <li>
                                    <a href="#">Third Level Item</a>
                                </li>
                            </ul>
                            <!-- /.nav-third-level -->
                        </li>
                    </ul>
                    <!-- /.nav-second-level -->
                </li>
                @{

                    var modules = Model.Where(moduleid => moduleid.moduleId == 0).ToList();
                    foreach (var mainmodule in modules)
                    {
                        <li>
                            @*<a href="#" class="menu-item"><i class="fa fa-user"></i> <span>@mainmodule.moduleName</span><span class="fa arrow"></span></a>*@
                            <a href="#" class="menu-item"><i class="fa fa-user"></i><span>@mainmodule.moduleName</span><span class="fa arrow"></span></a>
                            @{
                                var subModules = Model.Where(moduleid => moduleid.moduleId == mainmodule.subModuleId)
                                      .GroupBy(sModule => sModule.subModuleId)
                                      .Select(grp => grp.ToList()).ToList();
                            }
                            <ul class="nav nav-second-level collapse">


                                @{
                                    for (int k = 0; k < subModules.Count(); k++)
                                    {
                                        <li>
                                            <a href="#">@subModules[k][0].subModuleName<span class="fa arrow"></span></a>
                                            <ul class="nav nav-third-level collapse">
                                                @{
                                                    var subMenu = subModules[k].ToList();
                                                }
                                                <li>
                                                    <span class="entry"><span class="head">Entry</span></span>
                                                    <span class="list"><span class="head">List</span></span>
                                                </li>
                                                @{

                                                    foreach (var screens in subMenu)
                                                    {


                                                        <li>
                                                            <span class="entry">
                                                                <a href="~/@screens.addUrl" data-toggle="tooltip" title="@screens.screenName">@screens.screenName</a>
                                                            </span>




                                                            <span class="list"><a href="~/@screens.ViewUrl"><i class="fa fa-list-alt" aria-hidden="true"></i></a></span>
                                                        </li>


                                                    }
                                                }




                                            </ul>

                                        </li>


                                    }


                                }

                            </ul>

                        </li>


                    }
                }

            </ul>
        </div>
        <!-- /.sidebar-collapse -->
    </div>
    <!-- /.navbar-static-side -->
</nav>

ChitCare.UI/ChitCare.UI.Web/Areas/Masters/Views/Member/MemberRegistrationEdit.cshtml
@{
    ViewBag.Title = "MemberRegistrationEdit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>MemberRegistrationEdit</h2>

ChitCare.UI/ChitCare.UI.Web/Areas/Masters/Views/Member/MemberRegistrationEntry.cshtml
@{
    ViewBag.Title = "MemberRegistrationEntry";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

ChitCare.UI/ChitCare.UI.Web/Views/Shared/_Layout.cshtml
@using ChitCare.UI.ViewModels.Models;
@model IEnumerable<MenuViewModel>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Chitcare</title>

    <!-- Bootstrap Core CSS -->
    <link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">


    <link href="https://cdn.rawgit.com/tonystar/bootstrap-float-label/v4.0.0/dist/bootstrap-float-label.css" rel="stylesheet">
    
    <!-- MetisMenu CSS -->
    <link href="~/vendor/metisMenu/metisMenu.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="~/dist/css/chitcare-custom.css" rel="stylesheet">

    <!-- Morris Charts CSS -->
    <link href="~/vendor/morrisjs/morris.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="~/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    


</head>
<body>


    <div id="wrapper">
        <!-- Navigation -->
        @{
            Html.RenderAction("Menu", "Common");
        }
        <div id="page-wrapper" >
            @RenderBody()
            <footer>
                <div class="container-fluid">
                    <div class="col-sm-12">
                        <p class="text-center mb-0">Copyright 2001 - 2017 Kireeti Soft Technologies Ltd.</p>
                    </div>
                </div>
            </footer>
        </div>
    </div>

   
    <!-- /#wrapper -->
    <!-- jQuery -->
    <script src="~/vendor/jquery/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="~/vendor/bootstrap/js/bootstrap.min.js"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="~/vendor/metisMenu/metisMenu.min.js"></script>

    <!-- Morris Charts JavaScript -->
    <script src="~/vendor/raphael/raphael.min.js"></script>
    <script src="~/vendor/morrisjs/morris.min.js"></script>
    <script src="~/data/morris-data.js"></script>

    <!-- DataTables JavaScript -->
    <script src="~/vendor/datatables/js/jquery.dataTables.min.js"></script>
    <script src="~/vendor/datatables-plugins/dataTables.bootstrap.min.js"></script>
    <script src="~/vendor/datatables-responsive/dataTables.responsive.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="~/dist/js/chitcare-custom.js"></script>
    <script>
        $(document).ready(function () {
            $('#dataTables-example').DataTable({
                responsive: true,

            });
        });
    </script>
</body>

</html>