ChitCare.UI/ChitCare.UI.Web/ChitCare.UI.Web/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ChitCare.UI.ViewModels.Models;
using System.Threading.Tasks;
namespace ChitCare.UI.Web.Controllers
{
    public class MenuController : ChitCareController
    {
        // GET: Menu
        public  ActionResult Index()
        {
            List<MenuViewModel> menuList =  CHITCAREHttpClient.GetRequestSync<List<MenuViewModel>>("Menu/MainMenu");
            
            return View(menuList);
        }

       public PartialViewResult GetMenu()

        {
            List<MenuViewModel> menuList = CHITCAREHttpClient.GetRequestSync<List<MenuViewModel>>("Menu/MainMenu");

            return PartialView("GetMenu", menuList);
        }

    }
}

ChitCare.UI/ChitCare.UI.Web/ChitCare.UI.Web/Views/Shared/_Layout.cshtml
@using ChitCare.UI.ViewModels.Models;
@model IEnumerable<MenuViewModel>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Chitcare</title>

    <!-- Bootstrap Core CSS -->
    <link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">


    <link href="https://cdn.rawgit.com/tonystar/bootstrap-float-label/v4.0.0/dist/bootstrap-float-label.css" rel="stylesheet">
    
    <!-- MetisMenu CSS -->
    <link href="~/vendor/metisMenu/metisMenu.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="~/dist/css/chitcare-custom.css" rel="stylesheet">

    <!-- Morris Charts CSS -->
    <link href="~/vendor/morrisjs/morris.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="~/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    


</head>
<body>


    <div id="wrapper">
        <!-- Navigation -->
        @{
            Html.RenderAction("GetMenu", "Menu");
        }
        <div id="page-wrapper" style="height: 609px; margin-left: 0px; min-height: 559px;">
            @RenderBody()
            <footer>
                <div class="container-flung-model">
                    <div class="col-sm-12">
                        <p class="text-center mb-0">Copyright 2001 - 2017 Kireeti Soft Technologies Ltd.</p>
                    </div>
                </div>
            </footer>
        </div>
    </div>

   
    <!-- /#wrapper -->
    <!-- jQuery -->
    <script src="~/vendor/jquery/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="~/vendor/bootstrap/js/bootstrap.min.js"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="~/vendor/metisMenu/metisMenu.min.js"></script>

    <!-- Morris Charts JavaScript -->
    <script src="~/vendor/raphael/raphael.min.js"></script>
    <script src="~/vendor/morrisjs/morris.min.js"></script>
    <script src="~/data/morris-data.js"></script>

    <!-- DataTables JavaScript -->
    <script src="~/vendor/datatables/js/jquery.dataTables.min.js"></script>
    <script src="~/vendor/datatables-plugins/dataTables.bootstrap.min.js"></script>
    <script src="~/vendor/datatables-responsive/dataTables.responsive.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="~/dist/js/chitcare-custom.js"></script>
    <script>
        $(document).ready(function () {
            $('#dataTables-example').DataTable({
                responsive: true,

            });
        });
    </script>
</body>

</html>